[palletes.pywal]
color_fg0 = {foreground};
color_bg1 = {background};
color_bg3 = {color0};
color_red = {color1};
color_orange = {color2};
color_yellow = {color3};
color_green = {color4};
color_aqua = {color13};
color_blue = {color5};
color_purple = {color6};